apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: app
          image: gcr.io/global-song-354109/task3:prodd
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
---


apiVersion: "v1"
kind: "Service"
metadata:
  name: "hello-app-service"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "hello-app"
  type: "LoadBalancer"
  loadBalancerIP: ""